using Evidence.Nova.Common;

namespace GreenTransport.NovaForms.DefaultDetailForm
{


    public class DefaultDetailFormView : NovaViewBase
    {
        #region View Element Properties (Nova Auto Generated)

        /* THIS REGION IS AUTO-GENERATED BY TOOL Evidence.Nova.ViewPropertyCodeGenerator
        * DO NOT EDIT IT BY YOURSELF
        */

        public NovaForm FrmDefaultDetailForm
        {
            get { return base.FindElementByName<NovaForm>("frmDefaultDetailForm"); }
        }
        #endregion

    }
}

