using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Text;
using Evidence.Business;
using Evidence.Services;
using GlauxSoft.Business;
using System.Collections;
using myConst = GlauxSoft.GreenTransport.Repository.Constants;

namespace GlauxSoft.GreenTransport.Queries
{
    /// <summary>Class for query definition and access to query called VehicleGetById in evidence class Vehicle</summary>
    /// <remarks>Query names are unique over all evidence classes.</remarks>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("QueryBuilder", "1.35.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.Diagnostics.DebuggerDisplay("ClassName={ClassName}, QueryName=VehicleGetById")]
    [EvidenceQuery(UseRepoConstants = true)]
    public class VehicleGetById : QueryBase
    {
        //###########################################################################
        //# THIS CODE WAS AUTOGENERATED BY THE QUERYBUILDER TOOL.                   # 
        //# DO NOT CHANGE CODE MANUALLY. INSTEAD MAKE CHANGES THROUGH QUERYBUILDER. #
        //###########################################################################

        #region Properties


        /// <summary>
        /// Gets the class name of the complex query's root class.
        /// </summary>
        public override string ClassName
        {
            get
            {
                return myConst.Vehicle.CLASSNAME;
            }
        }

        /// <summary>
        /// Gets the comment that is attached to the complex query.
        /// </summary>
        public override string Comment
        {
            get
            {
                return "";
            }
        }

        #endregion //Properties

        #region Constructor

        // create an instance of this class via the QueryFactory
        internal VehicleGetById(QueryFactoryContext context)
            : base(context)
        {
        }

        #endregion //Constructor

        #region Methods

        /// <summary>
        /// Builds the native complex query as it is defined in the evidence repository.
        /// </summary>
        /// <returns>A new ComplexQuery instance.</returns>
        /// <exception cref="InvalidQueryException">occurs if the query is not valid.</exception>
        protected override ComplexQuery LoadQueryInternal()
        {
            // Checks all classes/attributes/enums/relations which are in use in this query.
            // If one item is missing, it will raise an InvalidQueryException with message: Invalid query: non-existing or forbidden items are used.
            // It will not provide the missing items in the exception text, because of sequrity reasons. 
            // The list of missing items will be written into the log.
            base.VisitClass(myConst.Vehicle.CLASSNAME);
            base.VisitAttribute(myConst.Vehicle.CLASSNAME, myConst.Vehicle.ATTR_ID);

            base.CheckVisitedItemsAndThrowOnError();

            // create query tree

            MLString prm810411d2ab714b038e1b51d39df5098eCaption = new MLString(new EvdLangId(7), "prmID", new EvdLangId(7));
            EvdParameter prm810411d2ab714b038e1b51d39df5098e = new EvdParameter("prm_810411d2ab714b038e1b51d39df5098e", ParameterType.Integer);
            prm810411d2ab714b038e1b51d39df5098e.Caption = prm810411d2ab714b038e1b51d39df5098eCaption;
            prm810411d2ab714b038e1b51d39df5098e.RowCount = 1;

            AttributeQuery query1 = AttributeQuery.Create(Directory.get_ClassDescriptor(myConst.Vehicle.CLASSNAME).ID);
            query1.AddRow(AttributeQueryRow.Create(Directory.get_AttrDescriptor(myConst.Vehicle.CLASSNAME, myConst.Vehicle.ATTR_ID), ComparisonOperators.EqualTo, prm810411d2ab714b038e1b51d39df5098e, LogicalConnector.LC_AND, null, Directory.get_ClassDescriptor(myConst.Vehicle.CLASSNAME).ID.GetValue()));

            ComplexQuery query0 = ComplexQuery.Create(query1);
            query0.Advanced = true;

            query0.Parameters.Add(prm810411d2ab714b038e1b51d39df5098e);

            query0.GetRootNodeQuery().ParamAskingType = ParameterAskingType.AskForAll;

            return query0;

        }


        /// <summary>
        /// Returns a prepared complex query ready for the execution. Any parameters is set and checked.
        /// If a parameter is of wrong type, missing or not provided by method input it will throw an exception.
        /// This behavior is the same as already implemented in core business object.
        /// </summary>
        public ComplexQuery GetComplexQuery(int prm810411d2ab714b038e1b51d39df5098e)
        {
            List<ParameterValue> parameters = new List<ParameterValue>();
            parameters.Add(new ParameterValue.IntegerParameter("prm_810411d2ab714b038e1b51d39df5098e", prm810411d2ab714b038e1b51d39df5098e));

            //return the result of the dynamic way
            return base.GetComplexQuery(parameters.ToArray());
        }

        /// <summary>
        /// Executes query "VehicleGetById" and returns result as list of business objects. 
        /// Type of business object is the type which is configured in business layer config for the 
        /// provided class id of this query.
        /// </summary>
        public List<BusinessObject> GetObjects(int prm810411d2ab714b038e1b51d39df5098e)
        {
            List<ParameterValue> parameters = new List<ParameterValue>();
            parameters.Add(new ParameterValue.IntegerParameter("prm_810411d2ab714b038e1b51d39df5098e", prm810411d2ab714b038e1b51d39df5098e));

            return base.GetObjects(parameters.ToArray());

        }

        /// <summary>
        /// Executes query "VehicleGetById" and returns result as list object business objects of type T.
        /// This method can be used with LightWeigthBusinessObjects too.
        /// </summary>
        public List<T> GetObjects<T>(int prm810411d2ab714b038e1b51d39df5098e)
            where T : CoreBusinessObject
        {
            List<ParameterValue> parameters = new List<ParameterValue>();
            parameters.Add(new ParameterValue.IntegerParameter("prm_810411d2ab714b038e1b51d39df5098e", prm810411d2ab714b038e1b51d39df5098e));

            //return the result of the dynamic way
            return base.GetObjects<T>(parameters.ToArray());
        }

        /// <summary>
        /// Returns a queryable instance for query "VehicleGetById". See <see cref="CoreBusinessObject.AsQueryable"/> for queryable usage.
        /// </summary>
        /// <typeparam name="BusinessObject">The business object type to get evidence class information and mapping result data to.</typeparam>
        public BusinessObjectQueryable<BusinessObject> AsQueryable<BusinessObject>(int prm810411d2ab714b038e1b51d39df5098e)
            where BusinessObject : CoreBusinessObject
        {
            List<ParameterValue> parameters = new List<ParameterValue>();
            parameters.Add(new ParameterValue.IntegerParameter("prm_810411d2ab714b038e1b51d39df5098e", prm810411d2ab714b038e1b51d39df5098e));
            return (BusinessObjectQueryable<BusinessObject>)AsQueryable<BusinessObject>(parameters.ToArray());
        }

        #endregion // Methods

    }


    #region QueryAccessor

    // static typing to support intellisense programming.
    public partial class VehicleQueryAccessor : QueryAccessorBase
    {
        /// <summary>
        /// </summary>
        public VehicleGetById VehicleGetById
        {
            get { return base.GetQuery<VehicleGetById>(); }
        }
    }

    #endregion // QueryAccessor

}