using Evidence.Nova.Common;

namespace GreenTransport.NovaForms.VehicleDetailsForm
{
    public class VehicleDetailsFormView : NovaViewBase
    {
        #region View Element Properties (Nova Auto Generated)

        /* THIS REGION IS AUTO-GENERATED BY TOOL Evidence.Nova.ViewPropertyCodeGenerator
        * DO NOT EDIT IT BY YOURSELF
        */

        public NovaForm FrmVehicleDetailsForm
        {
            get { return base.FindElementByName<NovaForm>("frmVehicleDetailsForm"); }
        }
        #endregion

        internal NovaCombo VehicleType
        {
            get { return FindElementByName<NovaCombo>(); }
        }

        internal NovaCombo Brand
        {
            get { return FindElementByName<NovaCombo>(); }
        }
        internal NovaText Model
        {
            get { return FindElementByName<NovaText>(); }
        }

       internal NovaRef RefLocation
        {
            get { return FindElementByName<NovaRef>(); }
        }
        // Car Properties
        internal NovaCombo VehicleClass
        {
            get { return FindElementByName<NovaCombo>(); }
        }
        internal NovaNumeric Efficiency
        {
            get { return FindElementByName<NovaNumeric>(); }
        }
        internal NovaNumeric Mileage
        {
            get { return FindElementByName<NovaNumeric>(); }
        }
        internal NovaNumeric QtPassengers
        {
            get { return FindElementByName<NovaNumeric>(); }
        }
        internal NovaNumeric PriceDay
        {
            get { return FindElementByName<NovaNumeric>(); }
        }
        internal NovaNumeric ServiceHours
        {
            get { return FindElementByName<NovaNumeric>(); }
        }
        internal NovaDateTime ProdDate
        {
            get { return FindElementByName<NovaDateTime>(); }
        }
    }
}