using System;
using System.Collections.Generic;
using System.Text;
using GlauxSoft.Business;

namespace GlauxSoft.GreenTransport.Queries
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("QueryBuilder", "1.35.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class QueryFactory : QueryFactoryBase
    {
        //###########################################################
        //# THIS CODE WAS AUTOGENERATED BY THE QUERYBUILDER TOOL    # 
        //# DO NOT CHANGE THE CODE MANUALLY.                        #
        //###########################################################

        private QueryFactory()
        {
            // query factory is static/singleton
        }

        public static QueryCollection AllQueries
        {
            get
            {
                return QueryFactoryBase.GetQueryNames();
            }
        }

        public static IQuery GetQueryByName(string name)
        {
            return QueryFactoryBase.GetQueryByNameInternal(name, false);
        }

        public static IQuery GetQueryByName(string name, bool returnNullIfNotFound)
        {
            return QueryFactoryBase.GetQueryByNameInternal(name, returnNullIfNotFound);
        }

    }
}